-- Seed data para Game-Hub & Services Ecosystem
-- Datos de prueba realistas para el proyecto

-- Hashes de contraseñas generados con bcrypt.hash("password123", 10)
-- Para generar nuevos hashes, usar: bcrypt.hash("password", 10)

-- 1. Perfiles de usuario (4 roles: admin, redactor, colaborador, suscriptor)
-- Limpiar primero para permitir actualizaciones
DELETE FROM profiles WHERE id IN ('admin-001', 'redactor-001', 'redactor-002', 'colaborador-001', 'colaborador-002', 'suscriptor-001', 'suscriptor-002', 'suscriptor-003');
INSERT INTO profiles (id, email, name, role, bio, location, website, avatar_url, password_hash, created_at, updated_at) VALUES
-- Admin
('admin-001', 'admin@gamehub.com', 'Carlos García', 'admin', 'Director editorial y fundador de GameHub. Apasionado por la industria desde los tiempos del NES.', 'Madrid, España', 'https://twitter.com/gamedirector', 'https://api.dicebear.com/7.x/avataaars/svg?seed=Carlos', '$2a$10$X7w3E8v9J2K5L6M4N1P8Qe9Z2Y5X8W1V0U3T4S5R6Q7W8E9R0T1Y2', NOW(), NOW()),
-- Redactores
('redactor-001', 'maria.lopez@gamehub.com', 'María López', 'redactor', 'Especialista en RPGs y juegos de rol. 10 años cubriendo E3 y Gamescom.', 'Barcelona, España', 'https://twitter.com/mariagaming', 'https://api.dicebear.com/7.x/avataaars/svg?seed=Maria', '$2a$10$A1B2C3D4E5F6G7H8I9J0K1L2M3N4O5P6Q7R8S9T0U1V2W3X4Y5Z6', NOW(), NOW()),
('redactor-002', 'alex.kim@gamehub.com', 'Alex Kim', 'redactor', 'Periodista de tecnología y gaming. Anteriormente en IGN y Kotaku.', 'Seúl, Corea del Sur', 'https://twitter.com/alexkimgaming', 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alex', '$2a$10$B2C3D4E5F6G7H8I9J0K1L2M3N4O5P6Q7R8S9T0U1V2W3X4Y5Z6A7', NOW(), NOW()),
-- Colaboradores
('colaborador-001', 'james.wilson@gmail.com', 'James Wilson', 'colaborador', 'Streamer y creador de contenido. 500K seguidores en Twitch.', 'London, UK', 'https://twitch.tv/jamesgaming', 'https://api.dicebear.com/7.x/avataaars/svg?seed=James', '$2a$10$C3D4E5F6G7H8I9J0K1L2M3N4O5P6Q7R8S9T0U1V2W3X4Y5Z6A7B8', NOW(), NOW()),
('colaborador-002', 'sofia.martinez@gamehub.com', 'Sofía Martínez', 'colaborador', 'Desarrolladora indie y consultora de diseño de juegos.', 'Buenos Aires, Argentina', 'https://sofiagames.dev', 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sofia', '$2a$10$D4E5F6G7H8I9J0K1L2M3N4O5P6Q7R8S9T0U1V2W3X4Y5Z6A7B8C9', NOW(), NOW()),
-- Suscriptores
('suscriptor-001', 'user1@gmail.com', 'Pedro Sánchez', 'suscriptor', 'Gamer casual desde hace 5 años. Fan de FIFA y CoD.', 'Valencia, España', NULL, 'https://api.dicebear.com/7.x/avataaars/svg?seed=Pedro', '$2a$10$E5F6G7H8I9J0K1L2M3N4O5P6Q7R8S9T0U1V2W3X4Y5Z6A7B8C9D0', NOW(), NOW()),
('suscriptor-002', 'user2@hotmail.com', 'Emma Thompson', 'suscriptor', 'Amante de los juegos indie y retro. Coleccionista de consolas.', 'Manchester, UK', NULL, 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emma', '$2a$10$F6G7H8I9J0K1L2M3N4O5P6Q7R8S9T0U1V2W3X4Y5Z6A7B8C9D0E1', NOW(), NOW()),
('suscriptor-003', 'user3@yahoo.com', 'Lucas Silva', 'suscriptor', 'Competitivo de Valorant y League of Legends. Rango Diamond.', 'São Paulo, Brasil', NULL, 'https://api.dicebear.com/7.x/avataaars/svg?seed=Lucas', '$2a$10$G7H8I9J0K1L2M3N4O5P6Q7R8S9T0U1V2W3X4Y5Z6A7B8C9D0E1F2', NOW(), NOW());

-- 2. Top 10 de los mejores juegos de la historia
DELETE FROM games WHERE id LIKE 'game-%';
INSERT INTO games (id, title, description, cover_image, release_date, genre, platform, press_score, user_score, category, created_at, updated_at) VALUES
('game-001', 'The Legend of Zelda: Ocarina of Time', 'Considerado por muchos como el mejor juego de todos los tiempos. Revolucionó el género de aventuras con su sistema Z-targeting y mundo 3D.', 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fhowlongtobeat.com%2Fgames%2F10035_The_Legend_of_Zelda_Ocarina_of_Time.png&f=1&nofb=1&ipt=21c8b8288d2c87b3964744b84d02436efb6a8649df653df29066e73bb603e39c', '1998-11-21', ARRAY['Aventura', 'Acción', 'RPG'], ARRAY['N64'], 99, 94, 'Top de la historia', NOW(), NOW()),
('game-002', 'Tetris', 'El puzzle más icónico de la historia. Simple, adictivo y atemporal. Creó el género de los juegos de puzzle.', 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.mobygames.com%2Fimages%2Fcovers%2Fl%2F16097-tetris-nes-front-cover.jpg&f=1&nofb=1&ipt=c168e8a690a5689f39c73f8c1e7b1a0e24c7fbbd2eca1b47687a9e189155ec51', '1984-06-06', ARRAY['Puzzle', 'Arcade'], ARRAY['NES', 'Game Boy', 'PC'], 96, 88, 'Top de la historia', NOW(), NOW()),
('game-003', 'Super Mario Bros.', 'El juego que salvó la industria de los videojuegos tras la crisis de 1983. Definió el género de plataformas.', 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fpre00.deviantart.net%2Feef9%2Fth%2Fpre%2Fi%2F2014%2F172%2F3%2Fb%2Fsuper_mario_bros_nes_cover_by_perrito_gatito-d7ndqiw.png&f=1&nofb=1&ipt=a3d179ebf6f6f83665392e2b814bd3756eaf1748370c5d6e1a4706a1166de173', '1985-09-13', ARRAY['Plataformas', 'Aventura'], ARRAY['NES'], 94, 90, 'Top de la historia', NOW(), NOW()),
('game-004', 'The Legend of Zelda: Breath of the Wild', 'Revolucionó los juegos de mundo abierto con su libertad sin precedentes y física emergente.', 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwallpapers.com%2Fimages%2Fhd%2Fultra-hd-breath-of-the-wild-game-cover-ny16mxrpbl6lo96p.jpg&f=1&nofb=1&ipt=512c85188805ff23ce02abb40a8d9233f456c884698d102fae8eec632732bd92', '2017-03-03', ARRAY['Aventura', 'Acción', 'Mundo Abierto'], ARRAY['Switch', 'Wii U'], 98, 95, 'Top de la historia', NOW(), NOW()),
('game-005', 'Red Dead Redemption 2', 'Una obra maestra narrativa con el mundo abierto más detallado jamás creado. La culminación del western interactivo.', 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fassets.vg247.com%2Fcurrent%2F2018%2F05%2Fred_dead_redemption_2_cover_art_1.jpg&f=1&nofb=1&ipt=20239d564637f6e7efe9c312f9cf24f8e14b56744f5cb4de00b4eb2bef262e6c', '2018-10-26', ARRAY['Acción', 'Aventura', 'Mundo Abierto'], ARRAY['PS4', 'Xbox One', 'PC'], 97, 88, 'Top de la historia', NOW(), NOW()),
('game-006', 'The Witcher 3: Wild Hunt', 'El estándar de oro de los RPG de mundo abierto. Narrativa profunda, mundo vasto y personajes memorables.', 'https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2Fwww.mobygames.com%2Fimages%2Fcovers%2Fl%2F392214-the-witcher-3-wild-hunt-xbox-one-front-cover.png&f=1&nofb=1&ipt=d5e03cb618686359056f8435b344c05fdb7ef7fa441e707c8fc353383d5c2f7f', '2015-05-19', ARRAY['RPG', 'Aventura', 'Mundo Abierto'], ARRAY['PC', 'PS4', 'Xbox One', 'Switch'], 92, 93, 'Top de la historia', NOW(), NOW()),
('game-007', 'Minecraft', 'El juego más vendido de la historia. Creatividad infinita en un mundo de bloques que ha capturado a generaciones.', 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fimages-wixmp-ed30a86b8c4ca887773594c2.wixmp.com%2Ff%2F38eb60f7-015f-4e9a-a98c-0f81cb883d0f%2Fdg3rj58-5cf5800a-6f42-42a4-9a1d-cc5d619c5d81.jpg%3Ftoken%3DeyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzM4ZWI2MGY3LTAxNWYtNGU5YS1hOThjLTBmODFjYjg4M2QwZlwvZGczcmo1OC01Y2Y1ODAwYS02ZjQyLTQyYTQtOWExZC1jYzVkNjE5YzVkODEuanBnIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.4u6Fga8fmpD-s6n7hoPLqvcRLEeOTo08DfKfMC0_Fl8&f=1&nofb=1&ipt=0f85415dd431b09d8aeb2120a20f8d3c1323341bfa9f588a1096c27c829aabb8', '2011-11-18', ARRAY['Sandbox', 'Supervivencia', 'Aventura'], ARRAY['PC', 'PS4', 'Xbox One', 'Switch', 'Mobile'], 93, 89, 'Top de la historia', NOW(), NOW()),
('game-008', 'Grand Theft Auto V', 'El juego de mundo abierto más influyente de la última década. Sátira social, humor negro y libertad total.', 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.gtabase.com%2Figallery%2F501-600%2FGTA_V_Official_Cover_Art-524-1920.jpg&f=1&nofb=1&ipt=9ffcaa129db28c36da19c39564f0660ad2012b631b2eff106896627cdffb9324', '2013-09-17', ARRAY['Acción', 'Aventura', 'Mundo Abierto'], ARRAY['PS3', 'Xbox 360', 'PS4', 'Xbox One', 'PC', 'PS5', 'Xbox Series X|S'], 97, 86, 'Top de la historia', NOW(), NOW()),
('game-009', 'The Last of Us', 'Una experiencia narrativa sin precedentes que elevó el medio al nivel del cine. Emocional, brutal y hermoso.', 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%2Fid%2FOIP.1j3CztzmArPjY4gwr02xFwHaLH%3Fpid%3DApi&f=1&ipt=821c58842f4df40674e670bed7f931e956e28fb761b659c017f60061f05e3c1b', '2013-06-14', ARRAY['Acción', 'Aventura', 'Survival Horror'], ARRAY['PS3', 'PS4'], 95, 92, 'Top de la historia', NOW(), NOW()),
('game-010', 'Half-Life 2', 'Revolucionó los FPS con su motor de física, narrativa integrada y diseño de niveles sin precedentes.', 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%2Fid%2FOIP.IoNfk8dPBT-yHsnGD1QZEQHaLH%3Fpid%3DApi&f=1&ipt=5d9df6679a26433e4a7dcec9f3ac23b4e9486a03a8cc200ba3aa5015d82f678b', '2004-11-16', ARRAY['Shooter', 'FPS', 'Ciencia Ficción'], ARRAY['PC'], 96, 90, 'Top de la historia', NOW(), NOW()),
-- Top 10 2020-2025
('game-011', 'Elden Ring', 'RPG de acción desarrollado por FromSoftware con un mundo abierto y mecánicas de combate similares a la serie Dark Souls.', 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fm.media-amazon.com%2Fimages%2FI%2F6110RSDn3PL.jpg&f=1&nofb=1&ipt=52d59e2f866dd28e5757914fa10c44da40451f9f88dd17513ab0e15ea6f7c1e4', '2022-02-25', ARRAY['RPG', 'Acción', 'Mundo Abierto'], ARRAY['PC', 'PS4', 'PS5', 'Xbox One', 'Xbox Series X|S'], 96, 91, 'Top 2020-2025', NOW(), NOW()),
('game-012', 'Baldur''s Gate 3', 'RPG basado en Dungeons & Dragons 5th Edition con narrativa ramificada y combate por turnos.', 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fstatic0.gamerantimages.com%2Fwordpress%2Fwp-content%2Fuploads%2F2023%2F10%2Fbaldurs-gate-3-cover.jpg&f=1&nofb=1&ipt=bbe5f6a9ecb85c6c9ab0918b68b3cf1434ea73a780a14dcb6f353a61ec2a7883', '2023-08-03', ARRAY['RPG', 'Estrategia', 'Aventura'], ARRAY['PC', 'PS5', 'Xbox Series X|S'], 96, 95, 'Top 2020-2025', NOW(), NOW()),
('game-013', 'The Last of Us Part II', 'Secuela del juego de acción y aventura que continúa la historia de Ellie en un mundo post-apocalíptico.', 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fstatic0.gamerantimages.com%2Fwordpress%2Fwp-content%2Fuploads%2F2024%2F12%2Fmixcollage-14-dec-2024-05-56-am-7891.jpg&f=1&nofb=1&ipt=f0f9d0225229db1e178182cc87fa10f66912f5ddc150490dbc9930b166efeff8', '2020-06-19', ARRAY['Acción', 'Aventura', 'Survival Horror'], ARRAY['PS4'], 93, 84, 'Top 2020-2025', NOW(), NOW()),
('game-014', 'Hades', 'Roguelike de acción desarrollado por Supergiant Games ambientado en la mitología griega.', 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.mobygames.com%2Fimages%2Fcovers%2Fl%2F757246-hades-windows-apps-front-cover.jpg&f=1&nofb=1&ipt=50b23107d7ebd2cc5a1cf73a61be31408c1326721d0bac4b02c3751bd1df718e', '2020-09-17', ARRAY['Roguelike', 'Acción', 'Indie'], ARRAY['PC', 'Switch', 'PS4', 'PS5', 'Xbox One'], 93, 96, 'Top 2020-2025', NOW(), NOW()),
('game-015', 'Clair Obscur: Expedition 33', 'JRPG francés con sistema de combate por turnos y mundo estilo fantasía inspirado en la Belle Époque.', 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fvgjournal.net%2Fmedia%2Fuploads%2Fgames%2Fimages%2F2025%2F04-April%2F18%2Fclair-obscur-expedition-33__cover__library_600x900_2x.jpg&f=1&nofb=1&ipt=b7532c2f7f5de548f66fd19a396dfc76e1f0daf9863eeb503fa54abc21da00cb', '2025-04-24', ARRAY['RPG', 'JRPG', 'Aventura'], ARRAY['PS5', 'Xbox Series X|S', 'PC'], 95, 88, 'Top 2020-2025', NOW(), NOW()),
('game-016', 'Hades II', 'Secuela del roguelike de acción que continúa la historia en la mitología griega.', 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fstatic0.gamerantimages.com%2Fwordpress%2Fwp-content%2Fuploads%2F2023%2F01%2Fhades2coverart.jpg&f=1&nofb=1&ipt=0c0612ba46011fa7e7098965fe7a8177c4e367c52836b15c60bfb99e39a03760', '2025-06-30', ARRAY['Roguelike', 'Acción', 'Indie'], ARRAY['PC', 'Switch', 'PS4', 'PS5'], 94, 95, 'Top 2020-2025', NOW(), NOW()),
('game-017', 'Ghost of Tsushima', 'Juego de acción y aventura ambientado en el Japón feudal durante la invasión mongola.', 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2F4kwallpapers.com%2Fimages%2Fwallpapers%2Fghost-of-tsushima-1440x2560-12072.jpg&f=1&nofb=1&ipt=327e0ab47c8c8c7d352f264b6abefbfde11beb95a22288785dfeece1c6e5fa75', '2020-07-17', ARRAY['Acción', 'Aventura', 'Mundo Abierto'], ARRAY['PS4', 'PS5', 'PC'], 85, 92, 'Top 2020-2025', NOW(), NOW()),
('game-018', 'Resident Evil Village', 'Octavo título principal de la serie Resident Evil que mezcla horror y acción en un pueblo gótico.', 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fwww.mobygames.com%2Fimages%2Fcovers%2Fl%2F736986-resident-evil-village-xbox-one-front-cover.jpg&f=1&nofb=1&ipt=1b95c9185f532ce8d4bc3fa184448eef9519fd1dbabfa046db1ee27281e4169d', '2021-05-07', ARRAY['Horror', 'Acción', 'Survival Horror'], ARRAY['PC', 'PS4', 'PS5', 'Xbox One', 'Xbox Series X|S'], 85, 87, 'Top 2020-2025', NOW(), NOW()),
('game-019', 'God of War Ragnarök', 'Secuela de God of War (2018) que continúa la historia de Kratos y Atreus en la mitología nórdica.', 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse4.mm.bing.net%2Fth%2Fid%2FOIP.2E2ZDcX4TtmFDeEt2spBgAHaLH%3Fpid%3DApi&f=1&ipt=eb55a23233e975b1943daa06e849eb895b5d5e4123f80969b73ea662b58ebec2', '2022-11-09', ARRAY['Acción', 'Aventura', 'Hack and Slash'], ARRAY['PS4', 'PS5'], 94, 89, 'Top 2020-2025', NOW(), NOW()),
('game-020', 'Final Fantasy VII Rebirth', 'Segunda parte del remake de Final Fantasy VII que expande la historia del mundo de Gaia.', 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fimages-wixmp-ed30a86b8c4ca887773594c2.wixmp.com%2Ff%2F1ea08e12-847b-4c43-8433-ff86b833fd7b%2Fdhg9j17-38918094-e5f9-48e0-9356-ca70dd83ca9b.jpg%3Ftoken%3DeyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzFlYTA4ZTEyLTg0N2ItNGM0My04NDMzLWZmODZiODMzZmQ3YlwvZGhnOWoxNy0zODkxODA5NC1lNWY5LTQ4ZTAtOTM1Ni1jYTcwZGQ4M2NhOWIuanBnIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.RN0oQOcBeHIB6K-XW-_cCz9L9Xk68u88AI2TPxXVNRA&f=1&nofb=1&ipt=51bd82c9d3e65bd8d4a2092d4dd5461f6503d462108db57b4dc6bf188121c584', '2024-02-29', ARRAY['RPG', 'JRPG', 'Aventura'], ARRAY['PS5'], 92, 93, 'Top 2020-2025', NOW(), NOW())
ON CONFLICT (id) DO NOTHING;

-- 3. Noticias (actualidad del sector)
INSERT INTO news_posts (id, title, slug, excerpt, content, cover_image, published, featured, views, author_id, created_at, updated_at) VALUES
('news-001', '[Bloomberg] Sony retrasa PS6 a 2028-2029', 'playstation-6-retraso-bloomberg-2028', 'Sony pospone su próxima consola por costes de memoria RAM y desarrollo de IA.', $$Según reportes de Bloomberg, Sony ha decidido retrasar el lanzamiento de PlayStation 6 hasta 2028-2029 debido al aumento en los costes de memoria RAM y a la necesidad de integrar capacidades de IA más avanzadas.

La empresa japonesa está evaluando nuevas arquitecturas que permitan mayor compatibilidad con el catálogo actual mientras mantiene la ventaja competitiva en gráficos y rendimiento.

Este retraso también da más tiempo a los estudios de primera para desarrollar juegos de lanzamiento que muestren el potencial de la nueva consola.$$, NULL, true, true, 25400, 'redactor-001', NOW() - INTERVAL '2 days', NOW()),
('news-002', 'Nintendo anuncia sucesor de Switch para 2025', 'nintendo-sucesor-switch-2025', 'La consola híbrida tendrá mejoras gráficas significativas y mantendrá el concepto portátil.', $$Nintendo ha confirmado que está desarrollando el sucesor de Switch, previsto para lanzarse en 2025. La nueva consola mantendrá el factor forma híbrido que hizo exitoso al original, pero con especificaciones mucho más potentes que permitirán juegos más ambiciosos.

Se espera que la nueva consola sea compatible con los juegos de Switch actuales, similar a cómo PS5 es compatible con PS4.$$, NULL, true, true, 12350, 'redactor-002', NOW() - INTERVAL '3 days', NOW()),
('news-003', 'Xbox Game Pass supera 40M suscriptores', 'xbox-game-pass-40-millones-2026', 'El servicio de suscripción de Microsoft continúa su crecimiento imparable en 2026.', $$Microsoft ha anunciado que Xbox Game Pass ha superado los 40 millones de suscriptores activos a principios de 2026. Este hito demuestra la viabilidad del modelo de suscripción en gaming, consolidándose como una de las plataformas más importantes del sector.

Phil Spencer, jefe de Xbox, destacó que el crecimiento se debe en parte a la expansión del servicio a más plataformas y a la inclusión de más títulos de primera el día de lanzamiento.$$, NULL, true, false, 18920, 'redactor-001', NOW() - INTERVAL '5 days', NOW()),
('news-004', 'El boom indie continúa en 2026', 'boom-indie-2026', 'Títulos independientes dominan las listas de mejores valorados del año.', $$2026 está consolidando la tendencia de los últimos años donde los juegos independientes lideran las críticas y premios. Títulos recientes como "Animal Well", "Pizza Tower" y nuevos proyectos de estudios pequeños están recibiendo aclamación universal.

La democratización de herramientas de desarrollo como Unity, Godot y Unreal Engine 5, junto con plataformas de distribución más accesibles, ha permitido que pequeños estudios compitan directamente con grandes publishers en calidad e innovación.$$, NULL, true, false, 6780, 'redactor-002', NOW() - INTERVAL '7 days', NOW()),
('news-005', 'IA en el desarrollo de juegos: ¿El futuro o la amenaza?', 'ia-desarrollo-juegos-futuro-amenaza', 'La inteligencia artificial promete revolucionar pero también preocupa a los desarrolladores.', $$La inteligencia artificial generativa está entrando en el desarrollo de juegos de formas que antes eran impensables. Desde generación de assets hasta creación de NPCs con comportamiento realista, las herramientas de IA prometen acelerar el desarrollo.

Sin embargo, muchos desarrolladores expresan preocupación sobre el impacto en el empleo y la calidad creativa del resultado final.$$, NULL, true, false, 5420, 'redactor-001', NOW() - INTERVAL '10 days', NOW())
ON CONFLICT (id) DO NOTHING;

-- 4. Posts de blog de opinión
DELETE FROM blog_posts WHERE id LIKE 'blog-%';
INSERT INTO blog_posts (id, title, slug, content, published, author_id, created_at, updated_at) VALUES
('blog-001', 'Por qué los Souls-like son el género más influyente de la década', 'soulslike-genero-influyente-decada', 'Desde Demon''s Souls hasta Elden Ring, el género creado por FromSoftware ha redefinido qué significa dificultad en videojuegos. Su influencia se extiende a juegos tan diversos como Starfield, God of War e incluso indie como Hollow Knight.

La clave del éxito no es solo la dificultad, sino el diseño de niveles interconectados, la narrativa ambiental y la satisfacción de superar obstáculos aparentemente imposibles. Los jugadores han aprendido a valorar el esfuerzo sobre la gratificación instantánea.

Este género ha enseñado a toda la industria que los jugadores están dispuestos a aceptar desafíos si el diseño es justo y la recompensa merecida.', true, 'colaborador-001', NOW() - INTERVAL '4 days', NOW()),
('blog-002', 'El declive de los AAA y el renacimiento de los AA', 'decline-aaa-renaissance-aa', 'Los presupuestos de los juegos AAA han alcanzado niveles insostenibles. Cuando un juego necesita vender 5 millones de copias solo para recuperar costes, el riesgo es demasiado alto. Esto explica por qué vemos tantas secuelas y tan poca innovación.

Los juegos AA (double-A) están llenando ese vacío: proyectos con presupuesto moderado pero visión artística clara. Títulos como Hi-Fi Rush, Pizza Tower y Sea of Stars demuestran que no necesitas 200 millones de dólares para hacer algo excelente.

Creo que el futuro de la industria está en estos proyectos medianos que pueden arriesgar más.', true, 'colaborador-002', NOW() - INTERVAL '8 days', NOW()),
('blog-003', 'Mi experiencia como streamer full-time durante un año', 'experiencia-streamer-fulltime-ano', 'Hace un año dejé mi trabajo corporativo para dedicarme a streaming a tiempo completo. Ha sido el año más difícil pero más gratificante de mi vida.

Lo que no te cuentan: no es solo jugar. Es edición, marketing, gestión de comunidad, negociación de sponsors y mantener una mentalidad saludable. Los días que no ganas espectadores duelen más que los días en los que no ganas dinero.

Pero cuando llegas a un hito, cuando la comunidad te apoya en un momento difícil, cuando un juego te hace reír con miles de personas... vale la pena. No es para todos, pero para mí es el mejor trabajo del mundo.', true, 'colaborador-001', NOW() - INTERVAL '12 days', NOW()),
('blog-004', 'La importancia de la accesibilidad en videojuegos', 'importancia-accesibilidad-videojuegos', 'Como diseñadora de juegos, veo a menudo cómo la accesibilidad se trata como una "extra" o algo opcional. Pero debería ser parte fundamental del diseño desde el inicio.

Juegos como The Last of Us Part II, God of War Ragnarök y Hades demuestran que las opciones de accesibilidad no restan valor a la experiencia; al contrario, permiten que más personas disfruten del arte que creamos.

Subtítulos, control remapeable, modo de alto contraste, dificultad ajustable... estas no son características "nice to have", son esenciales para que gaming sea verdaderamente para todos.', true, 'colaborador-002', NOW() - INTERVAL '15 days', NOW())
ON CONFLICT (id) DO NOTHING;

-- 5. Comentarios en blog
DELETE FROM comments WHERE id LIKE 'comment-%';
INSERT INTO comments (id, content, author_id, post_id, created_at, updated_at) VALUES
('comment-001', 'Totalmente de acuerdo. Elden Ring cambió mi forma de ver los juegos. Antes evitaba todo lo difícil, ahora busco el desafío.', 'suscriptor-001', 'blog-001', NOW() - INTERVAL '3 days', NOW()),
('comment-002', 'Interesante perspectiva sobre los AA. Creo que también hay espacio para ambos tipos de juegos, pero el punto sobre el riesgo es muy válido.', 'suscriptor-002', 'blog-002', NOW() - INTERVAL '7 days', NOW()),
('comment-003', '¡Felicidades por el año! Sigo tu stream desde hace tiempo y se nota el esfuerzo que pones. ¡Sigue así!', 'suscriptor-003', 'blog-003', NOW() - INTERVAL '11 days', NOW()),
('comment-004', 'Excelente artículo sobre accesibilidad. Como gamer con discapacidad visual, agradezco mucho cuando los desarrolladores piensan en nosotros.', 'suscriptor-001', 'blog-004', NOW() - INTERVAL '14 days', NOW()),
('comment-005', 'Los Souls-like no son para todos. Yo prefiero juegos que pueda disfrutar sin frustrarme. Cada uno sus gustos.', 'suscriptor-002', 'blog-001', NOW() - INTERVAL '2 days', NOW())
ON CONFLICT (id) DO NOTHING;

-- 6. Multimedia (vídeos, streams, trailers)
DELETE FROM multimedia WHERE id LIKE 'multimedia-%';
INSERT INTO multimedia (id, title, type, url, thumbnail, platform, featured, created_at) VALUES
('multimedia-001', 'GTA VI Trailer 2', 'trailer', 'https://www.youtube.com/watch?v=QiIebY4wmWg', 'https://i.ytimg.com/vi/QiIebY4wmWg/maxresdefault.jpg', 'YouTube', true, NOW() - INTERVAL '1 day'),
('multimedia-002', 'BG3 Honour Mode Clear - No Exploits', 'video', 'https://www.youtube.com/watch?v=r9XLbsFAm2A', 'https://i.ytimg.com/vi/r9XLbsFAm2A/maxresdefault.jpg', 'YouTube', true, NOW() - INTERVAL '3 days'),
('multimedia-003', 'Stream en vivo: Hollow Knight Silksong WR', 'stream', 'https://www.twitch.tv/wpnebula', 'https://static-cdn.jtvnw.net/previews-ttv/live_user_wpnebula.jpg', 'Twitch', false, NOW() - INTERVAL '6 hours'),
('multimedia-004', 'Clair Obscur: Expedition 33 GOTY Review', 'video', 'https://www.youtube.com/watch?v=3vqZLK9zhOc', 'https://i.ytimg.com/vi/3vqZLK9zhOc/maxresdefault.jpg', 'YouTube', false, NOW() - INTERVAL '5 days'),
('multimedia-005', 'Metroid Prime 4 Beyond - Overview', 'trailer', 'https://www.youtube.com/watch?v=7mBR0H1F5hs', 'https://i.ytimg.com/vi/7mBR0H1F5hs/maxresdefault.jpg', 'YouTube', true, NOW() - INTERVAL '2 days'),
('multimedia-006', 'Stream en vivo: BG3 Honour Mode', 'stream', 'https://www.twitch.tv/jamesgaming', 'https://static-cdn.jtvnw.net/previews-ttv/live_user_jamesgaming.jpg', 'Twitch', false, NOW() - INTERVAL '12 hours'),
('multimedia-009', 'Stream en vivo: Elden Ring DLC No Hit Run', 'stream', 'https://www.twitch.tv/fromsoftfan', 'https://static-cdn.jtvnw.net/previews-ttv/live_user_fromsoftfan.jpg', 'Twitch', false, NOW() - INTERVAL '3 hours'),
('multimedia-007', 'PS6 Devkit Analysis - Bloomberg Leaks', 'video', 'https://www.youtube.com/watch?v=ZeOEs9xVO0s', 'https://i.ytimg.com/vi/ZeOEs9xVO0s/maxresdefault.jpg', 'YouTube', false, NOW() - INTERVAL '8 days'),
('multimedia-008', 'Hollow Knight Silksong - Release', 'trailer', 'https://www.youtube.com/watch?v=yYgid2tsJFw', 'https://i.ytimg.com/vi/yYgid2tsJFw/maxresdefault.jpg', 'YouTube', true, NOW() - INTERVAL '4 days')
ON CONFLICT (id) DO NOTHING;

-- 7. Eventos (lanzamientos, ferias, convenciones)
DELETE FROM events WHERE id LIKE 'event-%';
INSERT INTO events (id, title, description, type, start_date, end_date, location, url, created_at) VALUES
('event-001', 'Gamescom 2026', 'La feria de videojuegos más grande de Europa con anuncios y demos jugables.', 'convention', '2026-08-26', '2026-08-30', 'Colonia, Alemania', 'https://www.gamescom.global', NOW()),
('event-002', 'Tokyo Game Show 2026', 'Convención anual de videojuegos en Japón con foco en títulos asiáticos.', 'convention', '2026-09-17', '2026-09-21', 'Chiba, Japón', 'https://tgs.nikkeibp.co.jp', NOW()),
('event-003', 'Lanzamiento: GTA VI', 'Fecha rumor según insider reports. El tan esperado regreso de la serie.', 'launch', '2026-11-19', NULL, 'Mundial', 'https://www.rockstargames.com/gta-vi', NOW()),
('event-004', 'The Game Awards 2026', 'Ceremonia de premios anual con anuncios mundiales.', 'convention', '2026-12-12', '2026-12-12', 'Los Ángeles, EE.UU.', 'https://thegameawards.com', NOW()),
('event-005', 'Lanzamiento: Metroid Prime 4 Beyond', 'El regreso de la serie tras años de desarrollo.', 'launch', '2026-09-21', NULL, 'Mundial', 'https://www.nintendo.com/metroid-prime-4', NOW())
ON CONFLICT (id) DO NOTHING;

-- 8. Mensajes de contacto
DELETE FROM contact_messages WHERE id LIKE 'contact-%';
INSERT INTO contact_messages (id, name, email, subject, message, read, created_at) VALUES
('contact-001', 'Ana García', 'ana.garcia@email.com', 'Sugerencia: Sección de retro gaming', 'Hola equipo de GameHub, me encanta la web pero me gustaría sugerir una sección dedicada a juegos retro y clásicos. Creo que habría mucho interés en la comunidad. ¡Seguiré visitando!', false, NOW() - INTERVAL '1 day'),
('contact-002', 'Miguel Rodríguez', 'miguel.rodriguez@company.com', 'Propuesta de colaboración', 'Buenos días, represento a una empresa de desarrollo indie y nos gustaría explorar posibilidades de colaboración para promocionar nuestro próximo juego. ¿Podrían indicarnos el proceso para anuncios o patrocinios?', false, NOW() - INTERVAL '3 days'),
('contact-003', 'Laura Chen', 'laura.chen@email.com', 'Reporte de bug en página de noticias', 'Hola, encontré un problema en la página de noticias: al hacer scroll, algunas imágenes no cargan correctamente en móvil. Usando iPhone 14 con Safari. ¡Gracias por el gran contenido!', false, NOW() - INTERVAL '5 days'),
('contact-004', 'Carlos Mendez', 'carlos.mendez@email.com', 'Pregunta sobre registro de redactores', 'Hola, soy periodista de tecnología y me gustaría saber cómo puedo aplicar para ser redactor colaborador en GameHub. Tengo experiencia en medios como IGN España y 3DJuegos.', false, NOW() - INTERVAL '7 days'),
('contact-005', 'Sophie Martin', 'sophie.martin@email.com', 'Felicitaciones', 'Solo quería dejar un mensaje de felicitación por el proyecto. Es exactamente lo que faltaba en la comunidad de habla hispana. El diseño es hermoso y el contenido de alta calidad. ¡Sigan así!', true, NOW() - INTERVAL '10 days');
